config/routes.rb
Rails.application.routes.draw do
  

  get 'users/:username', to: 'users#show', as: 'user'

  resources :items
  resources :pieces
  ActiveAdmin.routes(self)
  resources :tweets
  devise_for :users

  as :user do
    get     "signin", to:       'devise/sessions#new'
    
    delete  "signout", to:      'devise/sessions#destroy'     #Now you can use signout_path #MDM
    
    get     'signup', to:       'devise/registrations#new'
  end    

  
  root 'pages#home'
  

  get 'about', to: 'pages#about'
  
  get 'contact-us', to: 'pages#contact-us'

end

app/models/tweet.rb
class Tweet < ApplicationRecord
    #Make sure that you define this as a belongs_to relationship #MDM
  belongs_to :user
  
  # Create some validations to make sure the the content entered is non-black #MDM
  validates :user, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  # :authenticate_user comes from the devise documentation.  Make sure to authenticate the user for all actions except index and show #MDM
  before_action :authenticate_user!, except: [:index, :show]
  
  
  # Move the next line directly into each function #MDM
  # before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    # Add in this #MDM
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    # Use current_user below, so that new tweets are only created by the logged in user #MDM
    # @tweet = Tweet.new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
    # Add in this #MDM
    # Use current_user below, so that new tweets are only created by the logged in user #MDM
    @tweet = Tweet.find(params[:id])
    @tweet = current_user.tweets.find(params[:id])
    
  end

  # POST /tweets
  # POST /tweets.json
  def create
    # Use current_user below, so that new tweets are only created by the logged in user #MDM
    #@tweet = Tweet.new(tweet_params)
    @tweet = current_user.tweets.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    # Add in this #MDM
    @tweet = Tweet.find(params[:id])    
    
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    # Add in this #MDM
    # Use current_user below, so that new tweets are only created by the logged in user #MDM
    # @tweet = Tweet.find(params[:id])
    @tweet = current_user.tweets.find(params[:id])
  
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # Move the below to the above functions, then you can delete it. #MDM
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      # Remove the :user_id #MDM
      # params.require(:tweet).permit(:user_id, :content)
      params.require(:tweet).permit(:content)

    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_for(tweet) do |f| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--Add bootstrap formatting, form-group  and form-control#MDM-->
  <!-- By removing the following code, you actually remove teh need to specify a user_id when creating a new tweet #MDM
  <div class="form-group">
    <%= f.label :user_id %>
    <%= f.text_field :user_id, class: "form-control" %>
  </div>
  -->

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control" %>
  </div>

  <!--<div class="actions">-->
    <%= f.submit class: "btn btn-primary" %>
  <!--</div>-->
<% end %>

app/views/tweets/edit.html.erb
<div class="container">

    <h1>Editing Tweet</h1>
    
    <%= render 'form', tweet: @tweet %>
    
    <%= link_to 'Show', @tweet %> |
    <%= link_to 'Back', tweets_path %>

    
</div>

app/views/tweets/index.html.erb
<!--You can exclude the notice #MDM -->
<!--<p id="notice"><%= notice %></p>-->
<div class="container">
  
  <!--Add a new div class=row for nicer bootstrap styling-->
  <div class="row">
    <div class="col-md-4">
       <!--Use a bootstrap 4 card type #MDM -->
       <!--https://v4-alpha.getbootstrap.com/components/card/-->
       <div class="card card-block">
        <h4 class="card-title">Your Account</h4>
        <!--<p class="card-text">       <%= current_user.email %>  </p>-->
        <!--Make it display the username, not the email address. #MDM-->
        <!--<p class="card-text">       <%=current_user.username %>  </p>-->
        <!--Add the link_to and make sure to pass the user argument.  This is needed in order to set the username in the path. #MDM-->
        <p class="card-text">       <%= link_to current_user.username, user_path(current_user.username) %>  </p>

        <!--<a href="#" class="card-link">Card link</a>-->
        <!--<a href="#" class="card-link">Another link</a>-->
      </div>
    </div>
    <div class="col-md-8">
        
    
      
      <h1>Tweets</h1>
      
      <!-- Format the below with bootstrap by adding <table class="table"         s> #MDM-->
      <!--<table class="table">-->
        <!--Use Bootrap thread-inverse class-->
      <!--  <thead class="thread-inverse">-->
      <!--    <tr>-->
      <!--      <th>User</th>-->
      <!--      <th>Content</th>-->
      <!--      <th colspan="3"></th>-->
      <!--    </tr>-->
      <!--  </thead>-->
      <!--  <tbody>-->
      <!--   </tbody>-->
      <!--</table>-->


      <!--Makes more sense to show the New Tweet button only if user is logged-in #MDM -->
      <% if user_signed_in? %>
        <center><%= link_to 'New Tweet', new_tweet_path %></center>
      <% end %>
  
      <ul class="list-group">
          <% @tweets.each do |tweet| %>
            <%=  link_to tweet, class: "list-group-item list-group-item-action active" do %>
              <!--Add in the users email address #MDM-->
              <!--<td><%= tweet.user %></td>-->
              <!--<h5 class="list-group-item-heading"><%= tweet.user.email %></h5>-->
              
              <!--Show the username rather than the email-->
              <h5 class="list-group-item-heading"><%= tweet.user.username %></h5>
              
              <!-- if you want to avoid the exception screen, use .try : #MDM-->
              <!--<td><%= tweet.user.try(:email) %></td>-->
              
              <p class="list-group-item-text"><%= tweet.content %></p>
              <!--<p class="list-group-item-text"><%= link_to 'Show', tweet %>-->
            
              <!--If the currently logged in user is the same as the user who created thh tweet, show the EDIT * DESTROY button. #MDM-->
              <% if tweet.user == current_user %>
                <%= link_to 'Edit', edit_tweet_path(tweet) %>
                <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            <% end %>
            <p></p> 
          <% end %>
       </ul>

 
    </div>

  </div>

</div>

app/views/tweets/new.html.erb
<!--Place the following in the class="container" class for nicer bootstrap formatting. #MDM-->
<div class="container">

    <h1>New Tweet</h1>
    
    <%= render 'form', tweet: @tweet %>
    
    <%= link_to 'Back', tweets_path %>

</div>

app/views/tweets/show.html.erb
<!--These three bootstrap classes assist in lining things up.-->
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-md-8">
      <div class="card card-block">
        <!--<h4 class="card-title"><%= @tweet.user.email %></h4>-->
        <!--Show the .username, not the .email.-->
        <!--<h4 class="card-title"><%= @tweet.user.username %></h4>-->
        <!--Add the /username to the link here: #MDM-->
        <h4 class="card-title"><%= link_to @tweet.user.username, user_path(@tweet.user.username) %></h4>
        
        <p class="card-text"><%= @tweet.content %></p>
        <!--<a href="#" class="card-link">Card link</a>-->
        <% if @tweet.user == current_user %>
          <%= link_to 'Edit', edit_tweet_path(@tweet), class: "card-link" %>
          <!--Add in a delete tweet link-->
          <%= link_to 'Delete', @tweet method: :delete, class: "card-link" %>
          
        <% end %>        
        <!--<a href="#" class="card-link">Another link</a>-->
        <%= link_to 'Back', tweets_path, class: "card-link" %>
      </div>
        

      <!--<p id="notice"><%= notice %></p>-->
      
      <!--<p>-->
      <!--  <strong>User:</strong>-->
      <!--  <%= @tweet.user %>-->
      <!--</p>-->
      
      <!--<p>-->
      <!--  <strong>Content:</strong>-->
      <!--  <%= @tweet.content %>-->
      <!--</p>-->
      
      <!-- Only if the tweet belongs to the current user #MDM-->
      <!--<% if @tweet.user == current_user %>-->
      <!--  <%= link_to 'Edit', edit_tweet_path(@tweet) %> |-->
      <!--<% end %>-->
      
      <!--<%= link_to 'Back', tweets_path %>-->
    </div>
  </div>
</div>