config/routes.rb
Rails.application.routes.draw do
  

  get 'users/:username', to: 'users#show', as: 'user'

  resources :items
  resources :pieces
  ActiveAdmin.routes(self)
  resources :tweets
  devise_for :users

  as :user do
    get     "signin", to:       'devise/sessions#new'
    
    delete  "signout", to:      'devise/sessions#destroy'     #Now you can use signout_path #MDM
    
    get     'signup', to:       'devise/registrations#new'
  end    

  
  root 'pages#home'
  

  get 'about', to: 'pages#about'
  
  get 'contact-us', to: 'pages#contact-us'

end

app/models/piece.rb
# Generated this using a rails scaffold
# rails generate scaffold Piece title:string artist_name:string length:integer width:integer height:integer year:integer
class Piece < ApplicationRecord
  #Make sure that you define this as a belongs_to relationship #MDM
  belongs_to :user

end

app/controllers/pieces_controller.rb
# Generated this controller using the scaffold generator: #MDM
# rails generate scaffold Piece title:string artist_name:string length:integer width:integer height:integer year:integer
class PiecesController < ApplicationController
  # Use the authenticate_user action just like you did for the tweets.
  before_action :authenticate_user!, except: [:index, :show]

  
  # Update to following line to allow all except :index and :show #MDM
  # before_action :set_piece, only: [:show, :edit, :update, :destroy]
  

  # GET /pieces
  # GET /pieces.json
  def index
    @pieces = Piece.all
  end

  # GET /pieces/1
  # GET /pieces/1.json
  def show
    # Add in this #MDM
    @piece = Piece.find(params[:id])
  end

  # GET /pieces/new
  def new
    # Use current_user below, so that new tweets are only created by the logged in user #MDM
    @piece = Piece.new
    # @piece = current_user.pieces.new
  end

  # GET /pieces/1/edit
  def edit
    # Add in this #MDM
    # Use current_user below, so that new pieces are only created by the logged in user #MDM
    @piece = Piece.find(params[:id])
    @piece = current_user.pieces.find(params[:id])
  end

  # POST /pieces
  # POST /pieces.json
  def create
    # Use current_user below, so that new tweets are only created by the logged in user #MDM
    #@piece = Piece.new(piece_params)
    @piece = current_user.pieces.new(piece_params)


    respond_to do |format|
      if @piece.save
        format.html { redirect_to @piece, notice: 'Piece was successfully created.' }
        format.json { render :show, status: :created, location: @piece }
      else
        format.html { render :new }
        format.json { render json: @piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pieces/1
  # PATCH/PUT /pieces/1.json
  def update
    # Add in this #MDM
    @piece = Piece.find(params[:id])        
    
    respond_to do |format|
      if @piece.update(piece_params)
        format.html { redirect_to @piece, notice: 'Piece was successfully updated.' }
        format.json { render :show, status: :ok, location: @piece }
      else
        format.html { render :edit }
        format.json { render json: @piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pieces/1
  # DELETE /pieces/1.json
  def destroy
    # Add in this #MDM
    # Use current_user below, so that new pieces are only created by the logged in user #MDM
    # @piece = Piece.find(params[:id])  
    @piece = current_user.pieces.find(params[:id])
    
    @piece.destroy
    respond_to do |format|
      format.html { redirect_to pieces_url, notice: 'Piece was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_piece
      @piece = Piece.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def piece_params
     # Remove the :user_id #MDM
     params.require(:piece).permit(:title, :artist_name, :length, :width, :height, :year)

    end
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/views/pieces/_form.html.erb
<%= form_for(piece) do |f| %>
  <% if piece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(piece.errors.count, "error") %> prohibited this piece from being saved:</h2>

      <ul>
      <% piece.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :artist_name %>
    <%= f.text_field :artist_name %>
  </div>

  <div class="field">
    <%= f.label :length %>
    <%= f.number_field :length %>
  </div>

  <div class="field">
    <%= f.label :width %>
    <%= f.number_field :width %>
  </div>

  <div class="field">
    <%= f.label :height %>
    <%= f.number_field :height %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.number_field :year %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pieces/edit.html.erb
<div class="container">

    <h1>Editing Piece</h1>
    
    <%= render 'form', piece: @piece %>
    
    <%= link_to 'Show', @piece %> |
    <%= link_to 'Back', pieces_path %>


</div>

app/views/pieces/index.html.erb
<!--You can exclude the notice #MDM -->
<!--<p id="notice"><%= notice %></p>-->
<div class="container">


  <h1>Pieces</h1>
  
  <!-- Format the tables using class="table' to get nice boostrap formatting -->
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Artist name</th>
        <th>Length</th>
        <th>Width</th>
        <th>Height</th>
        <th>Year</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @pieces.each do |piece| %>
        <tr>
          <td><%= piece.title %></td>
          <td><%= piece.artist_name %></td>
          <td><%= piece.length %></td>
          <td><%= piece.width %></td>
          <td><%= piece.height %></td>
          <td><%= piece.year %></td>
          <td><%= link_to 'Show', piece %></td>
          <td><%= link_to 'Edit', edit_piece_path(piece) %></td>
          <td><%= link_to 'Destroy', piece, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'New Piece', new_piece_path %>

</div>

app/views/pieces/new.html.erb
<!--Place the following in the class="container" class for nicer bootstrap formatting. #MDM-->
<div class="container">

    <h1>New Piece</h1>
    
    <%= render 'form', piece: @piece %>
    
    <%= link_to 'Back', pieces_path %>

</div>

app/views/pieces/show.html.erb
<!--These three bootstrap classes assist in lining things up.-->
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-md-8">
      <div class="card card-block">
        <h4 class="card-title">Card title</h4>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="card-link">Card link</a>
        <a href="#" class="card-link">Another link</a>
      </div>
      
      
      <p id="notice"><%= notice %></p>
      
      <p>
        <strong>Title:</strong>
        <%= @piece.title %>
      </p>
      
      <p>
        <strong>Artist name:</strong>
        <%= @piece.artist_name %>
      </p>
      
      <p>
        <strong>Length:</strong>
        <%= @piece.length %>
      </p>
      
      <p>
        <strong>Width:</strong>
        <%= @piece.width %>
      </p>
      
      <p>
        <strong>Height:</strong>
        <%= @piece.height %>
      </p>
      
      <p>
        <strong>Year:</strong>
        <%= @piece.year %>
      </p>
      
      <%= link_to 'Edit', edit_piece_path(@piece) %> |
      <%= link_to 'Back', pieces_path %>

    </div>

  </div>

</div>