config/routes.rb
Rails.application.routes.draw do
  

  get 'users/:username', to: 'users#show', as: 'user'

  resources :items
  resources :pieces
  ActiveAdmin.routes(self)
  resources :tweets
  devise_for :users

  as :user do
    get     "signin", to:       'devise/sessions#new'
    
    delete  "signout", to:      'devise/sessions#destroy'     #Now you can use signout_path #MDM
    
    get     'signup', to:       'devise/registrations#new'
  end    

  
  root 'pages#home'
  

  get 'about', to: 'pages#about'
  
  get 'contact-us', to: 'pages#contact-us'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtDecoration</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!--For Google fonts #MDM-->
    <link href="https://fonts.googleapis.com/css?family=Shrikhand" rel="stylesheet">
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-dark bg-inverse">
      <div class="container">
        <%= link_to "ArtDecoration", root_path, class: "navbar-brand" %>
        <ul class="nav navbar-nav">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", "#", class: "nav-link" %></li>
          
          <!-- Show the logout button only if logged in #MDM -->
          <% if user_signed_in? %>
            <!-- Remember to destroy_user_session_path -->
            <!-- <li class="nav-item pull-md-right"><%= link_to "Log out", destroy_user_session_path,    method: :delete,  class: "nav-link" %></li>-->
            <li class="nav-item pull-md-right"><%= link_to "Log out", signout_path,    method: :delete,  class: "nav-link" %></li>
            
            
            
          <% else %>
            <!--<li class="nav-item pull-md-right"><%= link_to "Sign up", new_user_registration_path,                     class: "nav-link btn btn-primary" %></li>-->
            <!--<li class="nav-item pull-md-right"><%= link_to "Sign in", new_user_session_path,                          class: "nav-link" %></li>-->
            
            <!-- Remove the nav-link in the next line: #MDM -->
            <!--<li class="nav-item pull-md-right"><%= link_to "Sign up", signup_path,                        class: "nav-link btn btn-primary" %></li>-->
            <li class="nav-item pull-md-right"><%= link_to "Sign up", signup_path,                        class: "btn btn-primary" %></li>
            
            <li class="nav-item pull-md-right"><%= link_to "Sign in", signin_path,                        class: "nav-link" %></li>

          <% end %>
        </ul>
      </div>
    </nav>

    <!-- Flash Messages Needed for Devise #MDM -->
    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
    <% end %>

    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2016 ArtDecoration</p>
        </center>
      </div>
    </footer>

  </body>
</html>